---
- name: Provision Bastion host
  hosts: bastion
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - ansible
        state: present
        update_cache: yes

    - name: Clone Git repository
      git:
        repo: "https://github.com/sposdknl/ansible01-zbx-VanicekMatej"
        dest: /opt/repo
        version: main