Vagrant.configure("2") do |config|
  config.vm.define "zabbix-server" do |zbx|
    zbx.vm.box = "generic/almalinux9" 
    zbx.vm.hostname = "zabbix-server"
    zbx.vm.network "private_network", ip: "192.168.56.10"
    zbx.vm.provider "virtualbox" do |vb|
      vb.customize ["import", "zabbix_appliance.ova"]
    end
  end
end